### ISSUE TITLE
Reduce verbose jwt expired messages

### ISSUE THREAD

**Issue by phuhl** [apparts-js/apparts-types#3]
On every JWT expired, such an error is printed:

```
03/Mar/2021:15:28:11 +0000 - 401 GET /v/1/resource/%5B1%5D? HTTP/1.1 {} #-#
TokenExpiredError: jwt expired
    at /home/philipp/git/apparts/apparts-model-api/node_modules/jsonwebtoken/verify.js:152:21
    at getSecret (/home/philipp/git/apparts/apparts-model-api/node_modules/jsonwebtoken/verify.js:90:14)
    at module.exports (/home/philipp/git/apparts/apparts-model-api/node_modules/jsonwebtoken/verify.js:94:10)
    at prepare (/home/philipp/git/apparts/apparts-model-api/node_modules/@apparts/types/preparators/prepauth.js:96:15)
    at f (/home/philipp/git/apparts/apparts-model-api/node_modules/@apparts/types/preparators/preparator.js:88:26)
    at Layer.handle [as handle_request] (/home/philipp/git/apparts/apparts-admin/test-api/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/philipp/git/apparts/apparts-admin/test-api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/philipp/git/apparts/apparts-admin/test-api/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/philipp/git/apparts/apparts-admin/test-api/node_modules/express/lib/router/layer.js:95:5)
    at /home/philipp/git/apparts/apparts-admin/test-api/node_modules/express/lib/router/index.js:281:22 {
  expiredAt: 2021-03-03T15:03:13.000Z
}
```

That's a bit excessive, either a 401 from morgan (then, frontend-api should be adapted to never produce 401s in the first place) or nothing at all on the expected jwt expired might be in order.

**Comment by phuhl** [comment]
Not relevant anymore
